name: Deploy Lambda Function 

on:
  workflow_dispatch:   
  push:
    branches:
      - bala-dev       

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code from develop
        uses: actions/checkout@v2
        with:
          ref: develop   

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env from secrets
        run: echo "${{ secrets.DEV_ENV_FILE }}" > .env

      - name: Zip project for Lambda
        run: |
          zip -r publish.zip . -x "*.git*" ".github/*" "publish.zip"
          ls -lh publish.zip

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name node-dev \
            --zip-file fileb://publish.zip \
            --region ${{ secrets.AWS_REGION }}
