name: Manual Workflows 

on:
  workflow_dispatch:   # ✅ Show "Run workflow" button in GitHub Actions tab (on develop)
  push:
    branches:
      - bala-dev       # ✅ Auto-trigger when code is pushed to bala-dev branch

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create .env with secrets
        run: echo "${{ secrets.DEV_ENV_FILE }}" > .env

      - name: Zip project for deployment
        run: |
          zip -r publish.zip . -x "*.git*" "node_modules/*" "*.github/*"
          ls -lh publish.zip  # Optional: shows zip file size

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name node-dev \
            --zip-file fileb://publish.zip \
            --region ${{ secrets.AWS_REGION }}
